### ISSUE TITLE
self compiled version won't start - setOpenURL - NoSuchMethodError

### ISSUE THREAD

**Issue by ThomasChr** [lolo101/MsgViewer#125]
Can anyone tell me why this happens?
```
>java -jar msgviewer.jar
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.NoSuchMethodError: at/redeye/FrameWork/widgets/helpwindow/HyperlinkExecuter.setOpenUrl(Lat/redeye/FrameWork/widgets/helpwindow/OpenUrlInterface;)V 
(loaded from file:msgviewer.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@65d1339b) 
called from class at.redeye.Plugins.ShellExec.Plugin (loaded from file:msgviewer.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@65d1339b).
```
Starting the Release Version works just fine.
I compiled with openjdk 18 on a fresh Ubuntu 22.04

**Comment by lolo101** [comment]
Hi @ThomasChr!
The method `HyperlinkExecuter.setOpenUrl` has been recently removed (not yet released)
However, the error you mention shows that the method is actually invoked in `at.redeye.Plugins.ShellExec.Plugin`
I didn't detect that invocation because the source files of that plugin are not part of MsgViewer.

I need to investigate this issue more closer because those plugins are still quite obscure to me.

Thank you very much for the report!

**Comment by ThomasChr** [comment]
I‘m very glad that it wasn‘t just my own fault :-)
Tell me if I can help in any way!

**Comment by ThomasChr** [comment]
After your commits 9 hours ago the actual commit de3d082910822a3e69ae6d9da8df80aaf4a419c5 is working just fine.
I assume f99cb983403e592224573dddf6b4733babdda841 was the solution...

**Comment by lolo101** [comment]
Good to hear that your issue is actually fixed :)

Before making a release I need to push tests further because as far as I understand the code the ShellExec plugin is only activated on Windows.
If you run the master version on a Linux box it might work whereas it breaks on a Windows box.

**Comment by ThomasChr** [comment]
Yes. Absolutely!
I compiled on Linux but ran on Windows.
