### ISSUE TITLE
no instruction from command line

### ISSUE THREAD

**Issue by icegood** [lolo101/MsgViewer#7]
no instruction for command line build. 
No notes about support of formatted text

**Comment by lolo101** [comment]
Hello @icegood and thanks for your interest in the project.

I'm not sure to fully understand your issue. The project is a classic Maven project : in order to build it from command line you need to make sure you have a JDK 11 and Maven installed and run
```
mvn install
```
You can find a complete documentation on the official Maven site: https://maven.apache.org/

What do you mean with support of formatted text ? The project is about reading mail messages.
The supported mail formats are:
- msg (HUGE documentation here: https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxmsg/b046868c-9fbf-41ae-9ffb-8de2bd4eec82)
- eml (see https://tools.ietf.org/html/rfc5322)
- mbox (see http://qmail.org./man/man5/mbox.html)

Please, I'm sure I missed your point so dont hesitate to ask :)
