### ISSUE TITLE
Cannot open PDF file attachment

### ISSUE THREAD

**Issue by skalg** [lolo101/MsgViewer#9]
With 1.7.0 I cannot open PDF files attachment. It's working fine with 1.6.0.

There's no error message or anything, it's just not opening.

Thank you

**Comment by lolo101** [comment]
Hello @skalg 

You are right, it looks like a regression has found its way in the code :)
However note that attachment handling is platform-specific. After the fix is published if the problem persist please reopen the issue and specify the platform and messages from the console related to the file opening
